credentials:
  usernames:
    helmichiha:
      email: helmichiha@gmail.com
      name: Helmi chiha
      password: '$2b$12$8h8vT9ecTFoD.4ow0ZD82el30c5nQvxt.pKbg9K4e12Ejfve60.iK'
      adresse : '23 rue albert roussel 75017 Paris'
      CP : '75017'
    mahdihadjsassi:
      email: mahdihadjsassi1@gmail.com
      name: Mahdi Hadj Sassi
      password: '$2b$12$8h8vT9ecTFoD.4ow0ZD82el30c5nQvxt.pKbg9K4e12Ejfve60.iK'
      adresse: 'Kerkennah Sfax Tunisia'
      CP: '2021'



cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - helmichia@gmail.com
  - anisse9@gmail.com
